// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: nodesync/nodesyncproto/protos/nodesync.proto

package nodesyncproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCodes int32

const (
	ErrCodes_Unexpected           ErrCodes = 0
	ErrCodes_ExpectedCoordinator  ErrCodes = 1
	ErrCodes_UnsupportedStorage   ErrCodes = 2
	ErrCodes_SpaceDeleted         ErrCodes = 3
	ErrCodes_ArchiveUnavailable   ErrCodes = 4
	ErrCodes_ArchiveObjectMissing ErrCodes = 5
	ErrCodes_PeerIsNotNode        ErrCodes = 6
	ErrCodes_ErrorOffset          ErrCodes = 1000
)

// Enum value maps for ErrCodes.
var (
	ErrCodes_name = map[int32]string{
		0:    "Unexpected",
		1:    "ExpectedCoordinator",
		2:    "UnsupportedStorage",
		3:    "SpaceDeleted",
		4:    "ArchiveUnavailable",
		5:    "ArchiveObjectMissing",
		6:    "PeerIsNotNode",
		1000: "ErrorOffset",
	}
	ErrCodes_value = map[string]int32{
		"Unexpected":           0,
		"ExpectedCoordinator":  1,
		"UnsupportedStorage":   2,
		"SpaceDeleted":         3,
		"ArchiveUnavailable":   4,
		"ArchiveObjectMissing": 5,
		"PeerIsNotNode":        6,
		"ErrorOffset":          1000,
	}
)

func (x ErrCodes) Enum() *ErrCodes {
	p := new(ErrCodes)
	*p = x
	return p
}

func (x ErrCodes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCodes) Descriptor() protoreflect.EnumDescriptor {
	return file_nodesync_nodesyncproto_protos_nodesync_proto_enumTypes[0].Descriptor()
}

func (ErrCodes) Type() protoreflect.EnumType {
	return &file_nodesync_nodesyncproto_protos_nodesync_proto_enumTypes[0]
}

func (x ErrCodes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCodes.Descriptor instead.
func (ErrCodes) EnumDescriptor() ([]byte, []int) {
	return file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescGZIP(), []int{0}
}

type ColdSyncProtocolType int32

const (
	ColdSyncProtocolType_Pogreb         ColdSyncProtocolType = 0
	ColdSyncProtocolType_AnystoreSqlite ColdSyncProtocolType = 1
)

// Enum value maps for ColdSyncProtocolType.
var (
	ColdSyncProtocolType_name = map[int32]string{
		0: "Pogreb",
		1: "AnystoreSqlite",
	}
	ColdSyncProtocolType_value = map[string]int32{
		"Pogreb":         0,
		"AnystoreSqlite": 1,
	}
)

func (x ColdSyncProtocolType) Enum() *ColdSyncProtocolType {
	p := new(ColdSyncProtocolType)
	*p = x
	return p
}

func (x ColdSyncProtocolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColdSyncProtocolType) Descriptor() protoreflect.EnumDescriptor {
	return file_nodesync_nodesyncproto_protos_nodesync_proto_enumTypes[1].Descriptor()
}

func (ColdSyncProtocolType) Type() protoreflect.EnumType {
	return &file_nodesync_nodesyncproto_protos_nodesync_proto_enumTypes[1]
}

func (x ColdSyncProtocolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColdSyncProtocolType.Descriptor instead.
func (ColdSyncProtocolType) EnumDescriptor() ([]byte, []int) {
	return file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescGZIP(), []int{1}
}

type AdoptArchiveResult int32

const (
	// the snapshot was copied and registered
	AdoptArchiveResult_AdoptArchiveOk AdoptArchiveResult = 0
	// the receiver already holds a copy of the space with the same heads:
	// counts as a durable ACK for the sender
	AdoptArchiveResult_AdoptArchiveAlreadyHaveSame AdoptArchiveResult = 1
	// the receiver already holds a copy with different heads; the sender must
	// converge via tree sync before the handoff can be acknowledged
	AdoptArchiveResult_AdoptArchiveAlreadyHaveDiverged AdoptArchiveResult = 2
)

// Enum value maps for AdoptArchiveResult.
var (
	AdoptArchiveResult_name = map[int32]string{
		0: "AdoptArchiveOk",
		1: "AdoptArchiveAlreadyHaveSame",
		2: "AdoptArchiveAlreadyHaveDiverged",
	}
	AdoptArchiveResult_value = map[string]int32{
		"AdoptArchiveOk":                  0,
		"AdoptArchiveAlreadyHaveSame":     1,
		"AdoptArchiveAlreadyHaveDiverged": 2,
	}
)

func (x AdoptArchiveResult) Enum() *AdoptArchiveResult {
	p := new(AdoptArchiveResult)
	*p = x
	return p
}

func (x AdoptArchiveResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdoptArchiveResult) Descriptor() protoreflect.EnumDescriptor {
	return file_nodesync_nodesyncproto_protos_nodesync_proto_enumTypes[2].Descriptor()
}

func (AdoptArchiveResult) Type() protoreflect.EnumType {
	return &file_nodesync_nodesyncproto_protos_nodesync_proto_enumTypes[2]
}

func (x AdoptArchiveResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdoptArchiveResult.Descriptor instead.
func (AdoptArchiveResult) EnumDescriptor() ([]byte, []int) {
	return file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescGZIP(), []int{2}
}

// PartitionSyncRange presenting a request for one range
type PartitionSyncRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          uint64                 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            uint64                 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Elements      bool                   `protobuf:"varint,4,opt,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionSyncRange) Reset() {
	*x = PartitionSyncRange{}
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionSyncRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionSyncRange) ProtoMessage() {}

func (x *PartitionSyncRange) ProtoReflect() protoreflect.Message {
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionSyncRange.ProtoReflect.Descriptor instead.
func (*PartitionSyncRange) Descriptor() ([]byte, []int) {
	return file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescGZIP(), []int{0}
}

func (x *PartitionSyncRange) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *PartitionSyncRange) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *PartitionSyncRange) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PartitionSyncRange) GetElements() bool {
	if x != nil {
		return x.Elements
	}
	return false
}

// PartitionSyncResult presenting a response for one range
type PartitionSyncResult struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Hash          []byte                        `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Elements      []*PartitionSyncResultElement `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"`
	Count         uint32                        `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionSyncResult) Reset() {
	*x = PartitionSyncResult{}
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionSyncResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionSyncResult) ProtoMessage() {}

func (x *PartitionSyncResult) ProtoReflect() protoreflect.Message {
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionSyncResult.ProtoReflect.Descriptor instead.
func (*PartitionSyncResult) Descriptor() ([]byte, []int) {
	return file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescGZIP(), []int{1}
}

func (x *PartitionSyncResult) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *PartitionSyncResult) GetElements() []*PartitionSyncResultElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *PartitionSyncResult) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// PartitionSyncResultElement presenting state of one object
type PartitionSyncResultElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Head          string                 `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionSyncResultElement) Reset() {
	*x = PartitionSyncResultElement{}
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionSyncResultElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionSyncResultElement) ProtoMessage() {}

func (x *PartitionSyncResultElement) ProtoReflect() protoreflect.Message {
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionSyncResultElement.ProtoReflect.Descriptor instead.
func (*PartitionSyncResultElement) Descriptor() ([]byte, []int) {
	return file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescGZIP(), []int{2}
}

func (x *PartitionSyncResultElement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PartitionSyncResultElement) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

// HeadSyncRequest is a request for HeadSync
type PartitionSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   uint64                 `protobuf:"varint,1,opt,name=partitionId,proto3" json:"partitionId,omitempty"`
	Ranges        []*PartitionSyncRange  `protobuf:"bytes,2,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionSyncRequest) Reset() {
	*x = PartitionSyncRequest{}
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionSyncRequest) ProtoMessage() {}

func (x *PartitionSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionSyncRequest.ProtoReflect.Descriptor instead.
func (*PartitionSyncRequest) Descriptor() ([]byte, []int) {
	return file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescGZIP(), []int{3}
}

func (x *PartitionSyncRequest) GetPartitionId() uint64 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PartitionSyncRequest) GetRanges() []*PartitionSyncRange {
	if x != nil {
		return x.Ranges
	}
	return nil
}

// PartitionSyncResponse is a response for HeadSync
type PartitionSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PartitionSyncResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionSyncResponse) Reset() {
	*x = PartitionSyncResponse{}
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionSyncResponse) ProtoMessage() {}

func (x *PartitionSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionSyncResponse.ProtoReflect.Descriptor instead.
func (*PartitionSyncResponse) Descriptor() ([]byte, []int) {
	return file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescGZIP(), []int{4}
}

func (x *PartitionSyncResponse) GetResults() []*PartitionSyncResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ColdSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	ProtocolType  ColdSyncProtocolType   `protobuf:"varint,2,opt,name=protocolType,proto3,enum=anyNodeSync.ColdSyncProtocolType" json:"protocolType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColdSyncRequest) Reset() {
	*x = ColdSyncRequest{}
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColdSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColdSyncRequest) ProtoMessage() {}

func (x *ColdSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColdSyncRequest.ProtoReflect.Descriptor instead.
func (*ColdSyncRequest) Descriptor() ([]byte, []int) {
	return file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescGZIP(), []int{5}
}

func (x *ColdSyncRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *ColdSyncRequest) GetProtocolType() ColdSyncProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ColdSyncProtocolType_Pogreb
}

type ColdSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Crc32         uint32                 `protobuf:"varint,4,opt,name=crc32,proto3" json:"crc32,omitempty"`
	ProtocolType  ColdSyncProtocolType   `protobuf:"varint,5,opt,name=protocolType,proto3,enum=anyNodeSync.ColdSyncProtocolType" json:"protocolType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColdSyncResponse) Reset() {
	*x = ColdSyncResponse{}
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColdSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColdSyncResponse) ProtoMessage() {}

func (x *ColdSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColdSyncResponse.ProtoReflect.Descriptor instead.
func (*ColdSyncResponse) Descriptor() ([]byte, []int) {
	return file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescGZIP(), []int{6}
}

func (x *ColdSyncResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ColdSyncResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ColdSyncResponse) GetCrc32() uint32 {
	if x != nil {
		return x.Crc32
	}
	return 0
}

func (x *ColdSyncResponse) GetProtocolType() ColdSyncProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ColdSyncProtocolType_Pogreb
}

type AdoptArchiveRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	SpaceId string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	// srcKey is the full key of the gzipped snapshot within the shared bucket (sender's prefix)
	SrcKey string `protobuf:"bytes,2,opt,name=srcKey,proto3" json:"srcKey,omitempty"`
	// heads hashes of the space at snapshot time, as stored in the sender's index
	OldHash string `protobuf:"bytes,3,opt,name=oldHash,proto3" json:"oldHash,omitempty"`
	NewHash string `protobuf:"bytes,4,opt,name=newHash,proto3" json:"newHash,omitempty"`
	// eager asks the receiver to restore the space in background right away
	Eager            bool  `protobuf:"varint,5,opt,name=eager,proto3" json:"eager,omitempty"`
	CompressedSize   int64 `protobuf:"varint,6,opt,name=compressedSize,proto3" json:"compressedSize,omitempty"`
	UncompressedSize int64 `protobuf:"varint,7,opt,name=uncompressedSize,proto3" json:"uncompressedSize,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdoptArchiveRequest) Reset() {
	*x = AdoptArchiveRequest{}
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdoptArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdoptArchiveRequest) ProtoMessage() {}

func (x *AdoptArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdoptArchiveRequest.ProtoReflect.Descriptor instead.
func (*AdoptArchiveRequest) Descriptor() ([]byte, []int) {
	return file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescGZIP(), []int{7}
}

func (x *AdoptArchiveRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *AdoptArchiveRequest) GetSrcKey() string {
	if x != nil {
		return x.SrcKey
	}
	return ""
}

func (x *AdoptArchiveRequest) GetOldHash() string {
	if x != nil {
		return x.OldHash
	}
	return ""
}

func (x *AdoptArchiveRequest) GetNewHash() string {
	if x != nil {
		return x.NewHash
	}
	return ""
}

func (x *AdoptArchiveRequest) GetEager() bool {
	if x != nil {
		return x.Eager
	}
	return false
}

func (x *AdoptArchiveRequest) GetCompressedSize() int64 {
	if x != nil {
		return x.CompressedSize
	}
	return 0
}

func (x *AdoptArchiveRequest) GetUncompressedSize() int64 {
	if x != nil {
		return x.UncompressedSize
	}
	return 0
}

type AdoptArchiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        AdoptArchiveResult     `protobuf:"varint,1,opt,name=result,proto3,enum=anyNodeSync.AdoptArchiveResult" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdoptArchiveResponse) Reset() {
	*x = AdoptArchiveResponse{}
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdoptArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdoptArchiveResponse) ProtoMessage() {}

func (x *AdoptArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdoptArchiveResponse.ProtoReflect.Descriptor instead.
func (*AdoptArchiveResponse) Descriptor() ([]byte, []int) {
	return file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescGZIP(), []int{8}
}

func (x *AdoptArchiveResponse) GetResult() AdoptArchiveResult {
	if x != nil {
		return x.Result
	}
	return AdoptArchiveResult_AdoptArchiveOk
}

var File_nodesync_nodesyncproto_protos_nodesync_proto protoreflect.FileDescriptor

const file_nodesync_nodesyncproto_protos_nodesync_proto_rawDesc = "" +
	"\n" +
	",nodesync/nodesyncproto/protos/nodesync.proto\x12\vanyNodeSync\"j\n" +
	"\x12PartitionSyncRange\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x04R\x02to\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x1a\n" +
	"\belements\x18\x04 \x01(\bR\belements\"\x84\x01\n" +
	"\x13PartitionSyncResult\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12C\n" +
	"\belements\x18\x02 \x03(\v2'.anyNodeSync.PartitionSyncResultElementR\belements\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"@\n" +
	"\x1aPartitionSyncResultElement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04head\x18\x02 \x01(\tR\x04head\"q\n" +
	"\x14PartitionSyncRequest\x12 \n" +
	"\vpartitionId\x18\x01 \x01(\x04R\vpartitionId\x127\n" +
	"\x06ranges\x18\x02 \x03(\v2\x1f.anyNodeSync.PartitionSyncRangeR\x06ranges\"S\n" +
	"\x15PartitionSyncResponse\x12:\n" +
	"\aresults\x18\x01 \x03(\v2 .anyNodeSync.PartitionSyncResultR\aresults\"r\n" +
	"\x0fColdSyncRequest\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\x12E\n" +
	"\fprotocolType\x18\x02 \x01(\x0e2!.anyNodeSync.ColdSyncProtocolTypeR\fprotocolType\"\x9f\x01\n" +
	"\x10ColdSyncResponse\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x14\n" +
	"\x05crc32\x18\x04 \x01(\rR\x05crc32\x12E\n" +
	"\fprotocolType\x18\x05 \x01(\x0e2!.anyNodeSync.ColdSyncProtocolTypeR\fprotocolType\"\xe5\x01\n" +
	"\x13AdoptArchiveRequest\x12\x18\n" +
	"\aspaceId\x18\x01 \x01(\tR\aspaceId\x12\x16\n" +
	"\x06srcKey\x18\x02 \x01(\tR\x06srcKey\x12\x18\n" +
	"\aoldHash\x18\x03 \x01(\tR\aoldHash\x12\x18\n" +
	"\anewHash\x18\x04 \x01(\tR\anewHash\x12\x14\n" +
	"\x05eager\x18\x05 \x01(\bR\x05eager\x12&\n" +
	"\x0ecompressedSize\x18\x06 \x01(\x03R\x0ecompressedSize\x12*\n" +
	"\x10uncompressedSize\x18\a \x01(\x03R\x10uncompressedSize\"O\n" +
	"\x14AdoptArchiveResponse\x127\n" +
	"\x06result\x18\x01 \x01(\x0e2\x1f.anyNodeSync.AdoptArchiveResultR\x06result*\xb4\x01\n" +
	"\bErrCodes\x12\x0e\n" +
	"\n" +
	"Unexpected\x10\x00\x12\x17\n" +
	"\x13ExpectedCoordinator\x10\x01\x12\x16\n" +
	"\x12UnsupportedStorage\x10\x02\x12\x10\n" +
	"\fSpaceDeleted\x10\x03\x12\x16\n" +
	"\x12ArchiveUnavailable\x10\x04\x12\x18\n" +
	"\x14ArchiveObjectMissing\x10\x05\x12\x11\n" +
	"\rPeerIsNotNode\x10\x06\x12\x10\n" +
	"\vErrorOffset\x10\xe8\a*6\n" +
	"\x14ColdSyncProtocolType\x12\n" +
	"\n" +
	"\x06Pogreb\x10\x00\x12\x12\n" +
	"\x0eAnystoreSqlite\x10\x01*n\n" +
	"\x12AdoptArchiveResult\x12\x12\n" +
	"\x0eAdoptArchiveOk\x10\x00\x12\x1f\n" +
	"\x1bAdoptArchiveAlreadyHaveSame\x10\x01\x12#\n" +
	"\x1fAdoptArchiveAlreadyHaveDiverged\x10\x022\x82\x02\n" +
	"\bNodeSync\x12V\n" +
	"\rPartitionSync\x12!.anyNodeSync.PartitionSyncRequest\x1a\".anyNodeSync.PartitionSyncResponse\x12I\n" +
	"\bColdSync\x12\x1c.anyNodeSync.ColdSyncRequest\x1a\x1d.anyNodeSync.ColdSyncResponse0\x01\x12S\n" +
	"\fAdoptArchive\x12 .anyNodeSync.AdoptArchiveRequest\x1a!.anyNodeSync.AdoptArchiveResponseB\x18Z\x16nodesync/nodesyncprotob\x06proto3"

var (
	file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescOnce sync.Once
	file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescData []byte
)

func file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescGZIP() []byte {
	file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescOnce.Do(func() {
		file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodesync_nodesyncproto_protos_nodesync_proto_rawDesc), len(file_nodesync_nodesyncproto_protos_nodesync_proto_rawDesc)))
	})
	return file_nodesync_nodesyncproto_protos_nodesync_proto_rawDescData
}

var file_nodesync_nodesyncproto_protos_nodesync_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_nodesync_nodesyncproto_protos_nodesync_proto_goTypes = []any{
	(ErrCodes)(0),                      // 0: anyNodeSync.ErrCodes
	(ColdSyncProtocolType)(0),          // 1: anyNodeSync.ColdSyncProtocolType
	(AdoptArchiveResult)(0),            // 2: anyNodeSync.AdoptArchiveResult
	(*PartitionSyncRange)(nil),         // 3: anyNodeSync.PartitionSyncRange
	(*PartitionSyncResult)(nil),        // 4: anyNodeSync.PartitionSyncResult
	(*PartitionSyncResultElement)(nil), // 5: anyNodeSync.PartitionSyncResultElement
	(*PartitionSyncRequest)(nil),       // 6: anyNodeSync.PartitionSyncRequest
	(*PartitionSyncResponse)(nil),      // 7: anyNodeSync.PartitionSyncResponse
	(*ColdSyncRequest)(nil),            // 8: anyNodeSync.ColdSyncRequest
	(*ColdSyncResponse)(nil),           // 9: anyNodeSync.ColdSyncResponse
	(*AdoptArchiveRequest)(nil),        // 10: anyNodeSync.AdoptArchiveRequest
	(*AdoptArchiveResponse)(nil),       // 11: anyNodeSync.AdoptArchiveResponse
}
var file_nodesync_nodesyncproto_protos_nodesync_proto_depIdxs = []int32{
	5,  // 0: anyNodeSync.PartitionSyncResult.elements:type_name -> anyNodeSync.PartitionSyncResultElement
	3,  // 1: anyNodeSync.PartitionSyncRequest.ranges:type_name -> anyNodeSync.PartitionSyncRange
	4,  // 2: anyNodeSync.PartitionSyncResponse.results:type_name -> anyNodeSync.PartitionSyncResult
	1,  // 3: anyNodeSync.ColdSyncRequest.protocolType:type_name -> anyNodeSync.ColdSyncProtocolType
	1,  // 4: anyNodeSync.ColdSyncResponse.protocolType:type_name -> anyNodeSync.ColdSyncProtocolType
	2,  // 5: anyNodeSync.AdoptArchiveResponse.result:type_name -> anyNodeSync.AdoptArchiveResult
	6,  // 6: anyNodeSync.NodeSync.PartitionSync:input_type -> anyNodeSync.PartitionSyncRequest
	8,  // 7: anyNodeSync.NodeSync.ColdSync:input_type -> anyNodeSync.ColdSyncRequest
	10, // 8: anyNodeSync.NodeSync.AdoptArchive:input_type -> anyNodeSync.AdoptArchiveRequest
	7,  // 9: anyNodeSync.NodeSync.PartitionSync:output_type -> anyNodeSync.PartitionSyncResponse
	9,  // 10: anyNodeSync.NodeSync.ColdSync:output_type -> anyNodeSync.ColdSyncResponse
	11, // 11: anyNodeSync.NodeSync.AdoptArchive:output_type -> anyNodeSync.AdoptArchiveResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_nodesync_nodesyncproto_protos_nodesync_proto_init() }
func file_nodesync_nodesyncproto_protos_nodesync_proto_init() {
	if File_nodesync_nodesyncproto_protos_nodesync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodesync_nodesyncproto_protos_nodesync_proto_rawDesc), len(file_nodesync_nodesyncproto_protos_nodesync_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodesync_nodesyncproto_protos_nodesync_proto_goTypes,
		DependencyIndexes: file_nodesync_nodesyncproto_protos_nodesync_proto_depIdxs,
		EnumInfos:         file_nodesync_nodesyncproto_protos_nodesync_proto_enumTypes,
		MessageInfos:      file_nodesync_nodesyncproto_protos_nodesync_proto_msgTypes,
	}.Build()
	File_nodesync_nodesyncproto_protos_nodesync_proto = out.File
	file_nodesync_nodesyncproto_protos_nodesync_proto_goTypes = nil
	file_nodesync_nodesyncproto_protos_nodesync_proto_depIdxs = nil
}
