// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: debug/nodedebugrpc/nodedebugrpcproto/protos/nodedebugrpc.proto

package nodedebugrpcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DumpTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=documentId,proto3" json:"documentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpTreeRequest) Reset() {
	*x = DumpTreeRequest{}
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpTreeRequest) ProtoMessage() {}

func (x *DumpTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpTreeRequest.ProtoReflect.Descriptor instead.
func (*DumpTreeRequest) Descriptor() ([]byte, []int) {
	return file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescGZIP(), []int{0}
}

func (x *DumpTreeRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *DumpTreeRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type DumpTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dump          string                 `protobuf:"bytes,1,opt,name=dump,proto3" json:"dump,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpTreeResponse) Reset() {
	*x = DumpTreeResponse{}
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpTreeResponse) ProtoMessage() {}

func (x *DumpTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpTreeResponse.ProtoReflect.Descriptor instead.
func (*DumpTreeResponse) Descriptor() ([]byte, []int) {
	return file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescGZIP(), []int{1}
}

func (x *DumpTreeResponse) GetDump() string {
	if x != nil {
		return x.Dump
	}
	return ""
}

type AllTreesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllTreesRequest) Reset() {
	*x = AllTreesRequest{}
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllTreesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTreesRequest) ProtoMessage() {}

func (x *AllTreesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTreesRequest.ProtoReflect.Descriptor instead.
func (*AllTreesRequest) Descriptor() ([]byte, []int) {
	return file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescGZIP(), []int{2}
}

func (x *AllTreesRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type Tree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Heads         []string               `protobuf:"bytes,2,rep,name=heads,proto3" json:"heads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tree) Reset() {
	*x = Tree{}
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tree) ProtoMessage() {}

func (x *Tree) ProtoReflect() protoreflect.Message {
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tree.ProtoReflect.Descriptor instead.
func (*Tree) Descriptor() ([]byte, []int) {
	return file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescGZIP(), []int{3}
}

func (x *Tree) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tree) GetHeads() []string {
	if x != nil {
		return x.Heads
	}
	return nil
}

type AllTreesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trees         []*Tree                `protobuf:"bytes,1,rep,name=trees,proto3" json:"trees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllTreesResponse) Reset() {
	*x = AllTreesResponse{}
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllTreesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTreesResponse) ProtoMessage() {}

func (x *AllTreesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTreesResponse.ProtoReflect.Descriptor instead.
func (*AllTreesResponse) Descriptor() ([]byte, []int) {
	return file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescGZIP(), []int{4}
}

func (x *AllTreesResponse) GetTrees() []*Tree {
	if x != nil {
		return x.Trees
	}
	return nil
}

type AllSpacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllSpacesRequest) Reset() {
	*x = AllSpacesRequest{}
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllSpacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllSpacesRequest) ProtoMessage() {}

func (x *AllSpacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllSpacesRequest.ProtoReflect.Descriptor instead.
func (*AllSpacesRequest) Descriptor() ([]byte, []int) {
	return file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescGZIP(), []int{5}
}

type AllSpacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceIds      []string               `protobuf:"bytes,1,rep,name=spaceIds,proto3" json:"spaceIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllSpacesResponse) Reset() {
	*x = AllSpacesResponse{}
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllSpacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllSpacesResponse) ProtoMessage() {}

func (x *AllSpacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllSpacesResponse.ProtoReflect.Descriptor instead.
func (*AllSpacesResponse) Descriptor() ([]byte, []int) {
	return file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescGZIP(), []int{6}
}

func (x *AllSpacesResponse) GetSpaceIds() []string {
	if x != nil {
		return x.SpaceIds
	}
	return nil
}

type TreeParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=documentId,proto3" json:"documentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeParamsRequest) Reset() {
	*x = TreeParamsRequest{}
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeParamsRequest) ProtoMessage() {}

func (x *TreeParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeParamsRequest.ProtoReflect.Descriptor instead.
func (*TreeParamsRequest) Descriptor() ([]byte, []int) {
	return file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescGZIP(), []int{7}
}

func (x *TreeParamsRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *TreeParamsRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type TreeParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootId        string                 `protobuf:"bytes,1,opt,name=rootId,proto3" json:"rootId,omitempty"`
	HeadIds       []string               `protobuf:"bytes,2,rep,name=headIds,proto3" json:"headIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeParamsResponse) Reset() {
	*x = TreeParamsResponse{}
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeParamsResponse) ProtoMessage() {}

func (x *TreeParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeParamsResponse.ProtoReflect.Descriptor instead.
func (*TreeParamsResponse) Descriptor() ([]byte, []int) {
	return file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescGZIP(), []int{8}
}

func (x *TreeParamsResponse) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

func (x *TreeParamsResponse) GetHeadIds() []string {
	if x != nil {
		return x.HeadIds
	}
	return nil
}

type ForceNodeSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceNodeSyncRequest) Reset() {
	*x = ForceNodeSyncRequest{}
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceNodeSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceNodeSyncRequest) ProtoMessage() {}

func (x *ForceNodeSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceNodeSyncRequest.ProtoReflect.Descriptor instead.
func (*ForceNodeSyncRequest) Descriptor() ([]byte, []int) {
	return file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescGZIP(), []int{9}
}

type ForceNodeSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceNodeSyncResponse) Reset() {
	*x = ForceNodeSyncResponse{}
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceNodeSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceNodeSyncResponse) ProtoMessage() {}

func (x *ForceNodeSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceNodeSyncResponse.ProtoReflect.Descriptor instead.
func (*ForceNodeSyncResponse) Descriptor() ([]byte, []int) {
	return file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescGZIP(), []int{10}
}

type NodesAddressesBySpaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=spaceId,proto3" json:"spaceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodesAddressesBySpaceRequest) Reset() {
	*x = NodesAddressesBySpaceRequest{}
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodesAddressesBySpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesAddressesBySpaceRequest) ProtoMessage() {}

func (x *NodesAddressesBySpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesAddressesBySpaceRequest.ProtoReflect.Descriptor instead.
func (*NodesAddressesBySpaceRequest) Descriptor() ([]byte, []int) {
	return file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescGZIP(), []int{11}
}

func (x *NodesAddressesBySpaceRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type NodesAddressesBySpaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeAddresses []string               `protobuf:"bytes,1,rep,name=nodeAddresses,proto3" json:"nodeAddresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodesAddressesBySpaceResponse) Reset() {
	*x = NodesAddressesBySpaceResponse{}
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodesAddressesBySpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesAddressesBySpaceResponse) ProtoMessage() {}

func (x *NodesAddressesBySpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesAddressesBySpaceResponse.ProtoReflect.Descriptor instead.
func (*NodesAddressesBySpaceResponse) Descriptor() ([]byte, []int) {
	return file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescGZIP(), []int{12}
}

func (x *NodesAddressesBySpaceResponse) GetNodeAddresses() []string {
	if x != nil {
		return x.NodeAddresses
	}
	return nil
}

var File_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto protoreflect.FileDescriptor

var file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDesc = string([]byte{
	0x0a, 0x3e, 0x64, 0x65, 0x62, 0x75, 0x67, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x64, 0x65, 0x62, 0x75,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x64, 0x65, 0x62, 0x75, 0x67, 0x72, 0x70,
	0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6e, 0x6f,
	0x64, 0x65, 0x64, 0x65, 0x62, 0x75, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x22, 0x4b, 0x0a, 0x0f, 0x44, 0x75, 0x6d,
	0x70, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x26, 0x0a, 0x10, 0x44, 0x75, 0x6d, 0x70, 0x54, 0x72,
	0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x75,
	0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x75, 0x6d, 0x70, 0x22, 0x2b,
	0x0a, 0x0f, 0x41, 0x6c, 0x6c, 0x54, 0x72, 0x65, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x04, 0x54,
	0x72, 0x65, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x65, 0x61, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x68, 0x65, 0x61, 0x64, 0x73, 0x22, 0x37, 0x0a, 0x10, 0x41, 0x6c, 0x6c,
	0x54, 0x72, 0x65, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x05, 0x74, 0x72, 0x65, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x52, 0x05, 0x74, 0x72, 0x65,
	0x65, 0x73, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x6c, 0x6c, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2f, 0x0a, 0x11, 0x41, 0x6c, 0x6c, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x73, 0x22, 0x4d, 0x0a, 0x11, 0x54, 0x72, 0x65, 0x65, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x12, 0x54, 0x72, 0x65, 0x65, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x6f, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x49, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x49, 0x64, 0x73, 0x22, 0x16,
	0x0a, 0x14, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x38, 0x0a, 0x1c, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x42, 0x79, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x1d, 0x4e, 0x6f, 0x64,
	0x65, 0x73, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x42, 0x79, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x6f,
	0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0d, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73,
	0x32, 0xce, 0x03, 0x0a, 0x07, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x70, 0x69, 0x12, 0x3f, 0x0a, 0x08,
	0x44, 0x75, 0x6d, 0x70, 0x54, 0x72, 0x65, 0x65, 0x12, 0x18, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61,
	0x70, 0x69, 0x2e, 0x44, 0x75, 0x6d, 0x70, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x75, 0x6d,
	0x70, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a,
	0x0a, 0x54, 0x72, 0x65, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1a, 0x2e, 0x6e, 0x6f,
	0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70,
	0x69, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x41, 0x6c, 0x6c, 0x54, 0x72, 0x65, 0x65, 0x73,
	0x12, 0x18, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x6c, 0x6c, 0x54, 0x72,
	0x65, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6e, 0x6f, 0x64,
	0x65, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x6c, 0x6c, 0x54, 0x72, 0x65, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x41, 0x6c, 0x6c, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x73, 0x12, 0x19, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x6c, 0x6c,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x6c, 0x6c, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x46, 0x6f, 0x72,
	0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x1d, 0x2e, 0x6e, 0x6f, 0x64,
	0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x79,
	0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x61, 0x70, 0x69, 0x2e, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x79, 0x6e,
	0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x15, 0x4e, 0x6f, 0x64,
	0x65, 0x73, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x42, 0x79, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x25, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x73, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x42, 0x79, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x61, 0x70, 0x69, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x42, 0x79, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x26, 0x5a, 0x24, 0x64, 0x65, 0x62, 0x75, 0x67, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x64,
	0x65, 0x62, 0x75, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x64, 0x65, 0x62, 0x75,
	0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescOnce sync.Once
	file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescData []byte
)

func file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescGZIP() []byte {
	file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescOnce.Do(func() {
		file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDesc), len(file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDesc)))
	})
	return file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDescData
}

var file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_goTypes = []any{
	(*DumpTreeRequest)(nil),               // 0: nodeapi.DumpTreeRequest
	(*DumpTreeResponse)(nil),              // 1: nodeapi.DumpTreeResponse
	(*AllTreesRequest)(nil),               // 2: nodeapi.AllTreesRequest
	(*Tree)(nil),                          // 3: nodeapi.Tree
	(*AllTreesResponse)(nil),              // 4: nodeapi.AllTreesResponse
	(*AllSpacesRequest)(nil),              // 5: nodeapi.AllSpacesRequest
	(*AllSpacesResponse)(nil),             // 6: nodeapi.AllSpacesResponse
	(*TreeParamsRequest)(nil),             // 7: nodeapi.TreeParamsRequest
	(*TreeParamsResponse)(nil),            // 8: nodeapi.TreeParamsResponse
	(*ForceNodeSyncRequest)(nil),          // 9: nodeapi.ForceNodeSyncRequest
	(*ForceNodeSyncResponse)(nil),         // 10: nodeapi.ForceNodeSyncResponse
	(*NodesAddressesBySpaceRequest)(nil),  // 11: nodeapi.NodesAddressesBySpaceRequest
	(*NodesAddressesBySpaceResponse)(nil), // 12: nodeapi.NodesAddressesBySpaceResponse
}
var file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_depIdxs = []int32{
	3,  // 0: nodeapi.AllTreesResponse.trees:type_name -> nodeapi.Tree
	0,  // 1: nodeapi.NodeApi.DumpTree:input_type -> nodeapi.DumpTreeRequest
	7,  // 2: nodeapi.NodeApi.TreeParams:input_type -> nodeapi.TreeParamsRequest
	2,  // 3: nodeapi.NodeApi.AllTrees:input_type -> nodeapi.AllTreesRequest
	5,  // 4: nodeapi.NodeApi.AllSpaces:input_type -> nodeapi.AllSpacesRequest
	9,  // 5: nodeapi.NodeApi.ForceNodeSync:input_type -> nodeapi.ForceNodeSyncRequest
	11, // 6: nodeapi.NodeApi.NodesAddressesBySpace:input_type -> nodeapi.NodesAddressesBySpaceRequest
	1,  // 7: nodeapi.NodeApi.DumpTree:output_type -> nodeapi.DumpTreeResponse
	8,  // 8: nodeapi.NodeApi.TreeParams:output_type -> nodeapi.TreeParamsResponse
	4,  // 9: nodeapi.NodeApi.AllTrees:output_type -> nodeapi.AllTreesResponse
	6,  // 10: nodeapi.NodeApi.AllSpaces:output_type -> nodeapi.AllSpacesResponse
	10, // 11: nodeapi.NodeApi.ForceNodeSync:output_type -> nodeapi.ForceNodeSyncResponse
	12, // 12: nodeapi.NodeApi.NodesAddressesBySpace:output_type -> nodeapi.NodesAddressesBySpaceResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_init() }
func file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_init() {
	if File_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDesc), len(file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_goTypes,
		DependencyIndexes: file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_depIdxs,
		MessageInfos:      file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_msgTypes,
	}.Build()
	File_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto = out.File
	file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_goTypes = nil
	file_debug_nodedebugrpc_nodedebugrpcproto_protos_nodedebugrpc_proto_depIdxs = nil
}
