// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anyproto/any-sync-node/archive/adopter (interfaces: Adopter)
//
// Generated by this command:
//
//	mockgen -destination mock_adopter/mock_adopter.go github.com/anyproto/any-sync-node/archive/adopter Adopter
//

// Package mock_adopter is a generated GoMock package.
package mock_adopter

import (
	context "context"
	reflect "reflect"

	nodesyncproto "github.com/anyproto/any-sync-node/nodesync/nodesyncproto"
	app "github.com/anyproto/any-sync/app"
	gomock "go.uber.org/mock/gomock"
)

// MockAdopter is a mock of Adopter interface.
type MockAdopter struct {
	ctrl     *gomock.Controller
	recorder *MockAdopterMockRecorder
	isgomock struct{}
}

// MockAdopterMockRecorder is the mock recorder for MockAdopter.
type MockAdopterMockRecorder struct {
	mock *MockAdopter
}

// NewMockAdopter creates a new mock instance.
func NewMockAdopter(ctrl *gomock.Controller) *MockAdopter {
	mock := &MockAdopter{ctrl: ctrl}
	mock.recorder = &MockAdopterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdopter) EXPECT() *MockAdopterMockRecorder {
	return m.recorder
}

// AdoptArchive mocks base method.
func (m *MockAdopter) AdoptArchive(ctx context.Context, req *nodesyncproto.AdoptArchiveRequest) (*nodesyncproto.AdoptArchiveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdoptArchive", ctx, req)
	ret0, _ := ret[0].(*nodesyncproto.AdoptArchiveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdoptArchive indicates an expected call of AdoptArchive.
func (mr *MockAdopterMockRecorder) AdoptArchive(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdoptArchive", reflect.TypeOf((*MockAdopter)(nil).AdoptArchive), ctx, req)
}

// Init mocks base method.
func (m *MockAdopter) Init(a *app.App) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockAdopterMockRecorder) Init(a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockAdopter)(nil).Init), a)
}

// Name mocks base method.
func (m *MockAdopter) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockAdopterMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockAdopter)(nil).Name))
}
