// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anyproto/any-sync-node/nodesync/hotsync (interfaces: HotSync)

// Package mock_hotsync is a generated GoMock package.
package mock_hotsync

import (
	context "context"
	reflect "reflect"
	atomic "sync/atomic"

	app "github.com/anyproto/any-sync/app"
	gomock "go.uber.org/mock/gomock"
)

// MockHotSync is a mock of HotSync interface.
type MockHotSync struct {
	ctrl     *gomock.Controller
	recorder *MockHotSyncMockRecorder
}

// MockHotSyncMockRecorder is the mock recorder for MockHotSync.
type MockHotSyncMockRecorder struct {
	mock *MockHotSync
}

// NewMockHotSync creates a new mock instance.
func NewMockHotSync(ctrl *gomock.Controller) *MockHotSync {
	mock := &MockHotSync{ctrl: ctrl}
	mock.recorder = &MockHotSyncMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHotSync) EXPECT() *MockHotSyncMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockHotSync) Close(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockHotSyncMockRecorder) Close(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockHotSync)(nil).Close), arg0)
}

// Init mocks base method.
func (m *MockHotSync) Init(arg0 *app.App) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockHotSyncMockRecorder) Init(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockHotSync)(nil).Init), arg0)
}

// Name mocks base method.
func (m *MockHotSync) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockHotSyncMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockHotSync)(nil).Name))
}

// Run mocks base method.
func (m *MockHotSync) Run(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockHotSyncMockRecorder) Run(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockHotSync)(nil).Run), arg0)
}

// SetMetric mocks base method.
func (m *MockHotSync) SetMetric(arg0, arg1 *atomic.Uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMetric", arg0, arg1)
}

// SetMetric indicates an expected call of SetMetric.
func (mr *MockHotSyncMockRecorder) SetMetric(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMetric", reflect.TypeOf((*MockHotSync)(nil).SetMetric), arg0, arg1)
}

// UpdateQueue mocks base method.
func (m *MockHotSync) UpdateQueue(arg0 []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateQueue", arg0)
}

// UpdateQueue indicates an expected call of UpdateQueue.
func (mr *MockHotSyncMockRecorder) UpdateQueue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQueue", reflect.TypeOf((*MockHotSync)(nil).UpdateQueue), arg0)
}
